    fields
        (
       U
            {   mean        on;   prime2Mean  on;    base        time;      }
       T
            {   mean        on;   prime2Mean  on;    base        time;      }
       chi
            {   mean        on;   prime2Mean  on;    base        time;      }
       varZ
            {   mean        on;   prime2Mean  on;    base        time;      }
       Z
            {   mean        on;   prime2Mean  on;    base        time;      }
      CH4 
            {   mean        on;   prime2Mean  on;    base        time;      }
      N2
            {   mean        on;   prime2Mean  on;    base        time;      }
      O2 
            {   mean        on;   prime2Mean  on;    base        time;      }
      OH 
            {   mean        on;   prime2Mean  on;    base        time;      }
      H2 
            {   mean        on;   prime2Mean  on;    base        time;      }
      H2O 
            {   mean        on;   prime2Mean  on;    base        time;      }
      CO 
            {   mean        on;   prime2Mean  on;    base        time;      }
      CO2 
            {   mean        on;   prime2Mean  on;    base        time;      }
      NO
            {   mean        on;   prime2Mean  on;    base        time;      }
          );
